### PR TITLE
Add bridgehead and poem conflict fix

### PR DESCRIPTION
**Pull request by weijia-cheng**
Follow-up to discussion in https://github.com/standardebooks/john-henry-newman_verses-on-various-occasions/pull/4

### CODE REVIEW

**Comment by acabal** [comment]
Can you also add `z3998:hymn`? Thanks!

**Comment by weijia-cheng** [comment]
I did add hymn; did you mean verse? Wasn’t sure if that one should go in also.

______________________________

Weijia Cheng
(443) 636-7317
weijia05@yahoo.com
______________________________

**Comment by acabal** [comment]
Sorry, yes, I meant verse

**Comment by weijia-cheng** [comment]
Pushed a new version with verse as well

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
