### PR TITLE
Add guide to music scores

### PR DESCRIPTION
**Pull request by ACBSmith**
Resubmitting this PR to what I believe is the correct branch.

@acabal - I'm not sure where to put the files for guides, as the Shakespeare guide isn't in this group of files. I'm especially not sure, as this contains embedded images, which the rest of the guides doesn't.

I'm going to be writing a guide for adding Wiki links, so some general guidance about how-to guides would be useful.

### CODE REVIEW

**Comment by acabal** [comment]
This doesn't go in the manual, it goes in the SE website repo. The repo is in HTML, see that Shakespeare how-to for a template to follow. You can probably convert this straight to HTML with Pandoc or something like that.

**Comment by ACBSmith** [comment]
Oh, OK. I was going off of what Vince was doing with common issues page. Is there an established way to use the full set of manual typesetting features, such as tip boxes, within that? The Shakespeare guide doesn't have any of those, and it also doesn't have images. It's a short enough guide that I don't mind doing some manual formatting.

**Comment by acabal** [comment]
No, those are not available outside of the actual manual. Pages outside of the manual are more ad-hoc but just work with what you have.

**Comment by ACBSmith** [comment]
Is it possible to use the rst -> html compiling tools without running a local php server? I'm presuming the CSS for the produced is sitewide.

**Comment by acabal** [comment]
Try pandoc

**Comment by ACBSmith** [comment]
Thanks, that's worked wonders.

**Pull request closed without merging**
