### PR TITLE
Common issues

### PR DESCRIPTION
**Pull request by vr8hub**
Start a list of common issues encountered when producing from PD-era scans/transcriptions. Right now to keep things easy, I'm using the same formatting as the manual; we can change that later if need be. There are a couple of issues right now where the wrong/corrected examples are shells, I still have to find examples for them, but I wanted to go ahead and get this up so others could add to it.

Right now the categories are Punctuation, Capitalization, Elision, Diacritics, Headers, and Italics. If you have one that doesn't fine one of those, feel free to start a new category.

### CODE REVIEW

**Comment by acabal** [comment]
Sorry it took me so long to get to this, things have been busy this year!

This looks very good. This doesn't quite belong in "how-tos", so maybe we can just give it its own page in `/contribute/`. Can you use pandoc to convert it to HTML, and then create a pull request on the web repo to include this in there? You can follow the basic template from any of the how-to pages. I'll have a few things to add myself too. Then, we can link to it from the step by step guide.

**Comment by vr8hub** [comment]
No worries. I’ll work on it this week.

**Comment by acabal** [comment]
I lost track of this in my inbox and just rediscovered it. I think it's worth wrapping up to post to the site - what do you think?

**Comment by vr8hub** [comment]
Oh, wow, I actually thought you had already done that. I could have sworn I saw it a few months ago.

Yes, certainly, but I will have to regroup and re-remember what it is I still need to do. I’ll try to look at it this weekend. I’m trying to get the review of Plato wrapped up.

**Pull request closed without merging**
