### PR TITLE
s/include/including/

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by acabal** [comment]
It looks like there's a merge conflict, is this PR still valid?

**Comment by apasel422** [comment]
> It looks like there's a merge conflict, is this PR still valid?

Not sure what happened here. The typo still exists in your `next` branch. Feel free to fix it there directly.

**Comment by acabal** [comment]
What exactly is the typo? It doesn't say

**Comment by apasel422** [comment]
> What exactly is the typo? It doesn't say

In https://github.com/standardebooks/manual/blob/next/7-high-level-structural-patterns.rst#headers it says "All other sections, *include* the half title page if any, begin at..." instead of *including*.

**Comment by acabal** [comment]
OK thanks, this has been fixed!

**Pull request closed without merging**
